# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriasMacro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, null=True, unique=True)),
                ('categorias', models.ManyToManyField(to='website.Categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, null=True)),
                ('quantidade', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('dataCriacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('modoPreparo', models.TextField()),
                ('tempoPreparo', models.TimeField()),
                ('rendimento', models.PositiveIntegerField(null=True)),
                ('grauDificuldade', models.PositiveIntegerField()),
                ('avaliacao', models.PositiveIntegerField(default=0, null=True)),
                ('imagem', models.ImageField(null=True, upload_to=b'fotos')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Categorias')),
                ('ingredientes', models.ManyToManyField(to='website.Ingredientes')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='unidadeMedida',
            field=models.ManyToManyField(to='website.UnidadesMedida'),
        ),
    ]
