# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriasmacro',
            name='categorias',
        ),
        migrations.AddField(
            model_name='unidadesmedida',
            name='categorias',
            field=models.ManyToManyField(to='website.CategoriasMacro'),
        ),
    ]
